### PR TITLE
Added humidity sensor support

### PR DESCRIPTION
**Pull request by manuelsalvatori**
Hi this is my first pull request in GitHub so I apology if I did something wrong.
I'm using your library and soon I'll add more devices support.
I have problems, trying to use this library with ASP.net Core, so for now I'm using a custom version I re skinned, I'm still not familiar with net standard/core.

### CODE REVIEW

**Comment by 1iveowl** [comment]
Thanks I appreciate the contribution 👍 

Could you please open an issues on the ASP.NET part? It should work and if it doesn't I'll try and fix it.

**Comment by 1iveowl** [comment]
I've added a library specifically for .NET Core and relased NuGet v0.7 that includes your contribution for Humidity device/service. 

Please let me know how this test our in your set up.

Thank you

**Comment by manuelsalvatori** [comment]
I'm testing it right now, thank you very much.
I want to go through your changes to try to understand what I was doing
wrong.
I'll keep you posted.
M

**Comment by 1iveowl** [comment]
I'm not sure you did anything wrong. .NET Standard/.NETCore is still new and the tools is still work-in-progress.

Anyhow, it's important that when you test this project that you reference the NuGet and not the project itself. Some of the work that goes on to match the right library to your project is handæed by NuGet ;-)

**Comment by 1iveowl** [comment]
And one extra thing. 

This library is based on "Bait and Switch" pattern. Which is a bit tricky but there is a great blog post on the subject here: : [The Bait and Switch PCL Trick](http://log.paulbetts.org/the-bait-and-switch-pcl-trick/)

**Comment by manuelsalvatori** [comment]
Hi, thank you, yes I read that article and actually I managed to create my
own additional project that overrides the few classes used to get the
controllers or to create the hash for the auth.
Currently when using the 0.7.0 and in the nuget package I get only
UpnpModels, nothing with the VeraController classes.

This is my project.json, and notice that I tried also with NETCore.APP
1.0.1.

{
  "dependencies": {
    "Microsoft.AspNet.Mvc.Core": "6.0.0-rc1-final",
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.NETCore.App": "1.1.0",
    "VeraControl.PCL": "0.7.0"
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "netcoreapp1.1": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder
%publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}


I'm I missing something?


Thanks

M

**Comment by manuelsalvatori** [comment]
No problem at all, actually sorry if I'm bothering.

**Comment by 1iveowl** [comment]
Not at all. I appreciate the feedback.

0.71 has been release to NuGet.Org. Please let me know if things are better now.

**Comment by manuelsalvatori** [comment]
I needed to add Automapper to the main project that uses the VeraControl
nuget package, because it was throwing an exception when debugging and also
running form the publish folder (in which there is the Automapper.dll).

Now I get the exception:
{System.NotImplementedException: Not implemented in shared library. See
platform specific libraries.
   at VeraControl.Extensions.SecurityExtension.Sha1Hash(String value)
   at
VeraControl.Model.UpnpService.VeraControl.Model.IdentityPackage.<GetIdentityPackage>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at
VeraControl.Service.VeraControlService.<GetControllers>d__8.MoveNext()}

Running on win7-x64, is it normal?

The implementation I was using In my own project is:

        internal static string Sha1Hash(this string value)
        {
            var sha1 = System.Security.Cryptography.SHA1.Create();
            var hash = sha1.ComputeHash(Encoding.UTF8.GetBytes(value));
            return BitConverter.ToString(hash).Replace("-",
string.Empty).ToLower();
        }

This was the implementation I was using for the VeraContro.Shared /
SecurityExtension.
What do you suggest me to do?
Should I create a new Foundation project specifically for net core?

Thanks
M

**Comment by 1iveowl** [comment]
Hmm, looks like there is a crypto library reference missing. I probably need to add this to the list of references needed for the .NET Standard 1.6 library. Let me look into it. 

I will need to set up a more detailed testing in my end. My bad that it didn't test probably. I thought I could get away with a quick-fix - experience have shown me that one rarely can ;-)

I'll look at it tomorrow.

**Comment by 1iveowl** [comment]
So I did some testing and I fixed the SHA1 bug in NuGet 0.7.4.

I still don't understand why AutoMapper is not installed when referencing the NuGet, not do I know how to fix it, but I am assuming that it is a tooling issue or an issue with AutoMapper. The reason I think it is an issue with Automapper is that it work if I add only Automapper. I don't have to add JSON.NET which is just a vital?!

**Comment by 1iveowl** [comment]
Ahh. Found the bug. I was referincing AutoMapper 5.1.1 in my Nuget Spec. Changing the reference to 5.2 fixed the issue. 

NuGet 0.7.5 passes all my test. I hope it will for you too.

Thanks again.

**Comment by manuelsalvatori** [comment]
Great job, it works perfectly now.
Thank you very much, have a good time.

**Pull request merged**
